sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - '4'
before_install:
  - npm i -g npm@^3.0.0
  - npm i --save-dev travis-after-all
before_script:
  - npm prune
after_script:
  - |
      set +e
      declare exitCode;
      $(npm bin)/travis-after-all
      exitCode=$?
      if [ "$exitCode" -eq 0 ]; then
        if [[ ($TRAVIS_PULL_REQUEST == false) ]] ; then
          sh ./.scripts/trigger-travis.sh goodmind check-types $TRAVIS_TOKEN
        fi
      fi
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
